name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests  # Este paso ejecuta las pruebas unitarias
        run: |
          python -m unittest discover -s tests -p "*.py"

      - name: Deploy to EC2 Instance
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.BACKEND_SSH_HOST }}
          EC2_USER: ${{ secrets.USER_NAME }}
          APP_DIR: /home/ubuntu/aws-backend  
          APP_FILE: app.py
          ENVIRONMENT: production
      
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              # Acceder al directorio del proyecto
              cd awsBackend && ls || exit 1

              # Activar el entorno virtual
              source venv/bin/activate || exit 2

              # Actualizar el código desde la rama main
              git fetch --all || exit 3
              git reset --hard origin/main || exit 4
              git pull origin main || exit 5

              # Instalar dependencias necesarias
              pip install -r requirements.txt || exit 6

              # Detener cualquier proceso que esté usando el puerto 5000
              sudo fuser -k 5000/tcp || exit 7

              # Ejecutar la aplicación Flask
              gunicorn -b 0.0.0.0:5000 app:app --daemon || exit 8
              
              '

